server:
  port: 8191
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jdgonzaleza/microservice-config-store
          search-paths:
           - 'service-config/*service'